### ISSUE TITLE
Fail to run on python3.8

### ISSUE THREAD

**Issue by synodriver** [FYWinds/nonebot-plugin-atri#1]
[这是3.9的新方法吧](https://github.com/FYWinds/nonebot-plugin-atri/blob/master/nonebot_plugin_atri/data.py#L7)

当然，对于linux的还得记得文件名乱码问题，使用convmv -f gbk -t utf-8 -r --notest ./voice/

**Comment by FYWinds** [comment]
linux下亲测无文件名编码导致的乱码问题

**Comment by synodriver** [comment]
啊那就是winscp背大锅（

**Comment by FYWinds** [comment]
啊这，您可以通过pip直接安装（

**Comment by synodriver** [comment]
是魔改，我魔改了插件（

**Comment by FYWinds** [comment]
欢迎PR
其实这是低技术力的屑作罢了，唯一价值可能只有语音了（悲

**Comment by synodriver** [comment]
> 欢迎PR
> 其实这是低技术力的屑作罢了，唯一价值可能只有语音了（悲

确实，我挪用了语音（
