### ISSUE TITLE
更改插件出现错误

### ISSUE THREAD

**Issue by HuParry** [FYWinds/nonebot-plugin-atri#2]
请问为什么我把text和voice换成了我自己所保存的一些.mp3文件后就出现了严重的报错？我严格按照了原插件的格式进行更换。

**Comment by FYWinds** [comment]
请将报错的Traceback发出来以便分析

**Comment by HuParry** [comment]
> 请将报错的Traceback发出来以便分析

如图，我弄了两个mp3音频，并且把json文件内容也篡改了。但出现了error。
![Uploading 57A2E4CD-88BB-4501-B2A3-2552E2E96350.png…]()

**Comment by HuParry** [comment]
![CEC0681B-BCC4-4260-823F-C57B8C04B458](https://user-images.githubusercontent.com/103566602/164709745-a0ffda3a-3fa8-4d4f-bcff-43618b748f60.png)
![D4602C3A-1DF5-4711-8866-0FAE551CD1DC](https://user-images.githubusercontent.com/103566602/164709750-09b57e97-1dbe-4abd-98d9-e07948c4d1c8.png)

**Comment by HuParry** [comment]
![Uploading 11A9E1BF-FA41-4CD6-AC86-31C4B029374C.png…]()

**Comment by FYWinds** [comment]
这是由于数量过少导致的，请确保至少有三条数据，我这里为了增加随机性对结果的前三条进行了随机选择，因此会出现数组越界的情况
也可以删去`__init__.py`第33行
```python
list(diff_sorted.keys())[2],
```

**Comment by HuParry** [comment]
> 这是由于数量过少导致的，请确保至少有三条数据，我这里为了增加随机性对结果的前三条进行了随机选择，因此会出现数组越界的情况 也可以删去`__init__.py`第33行
> 
> ```python
> list(diff_sorted.keys())[2],
> ```

好的，谢谢解答🙏
